/**
 * THE LAWRENCE Platform Engineering Program.
 *
 * The executable backlog. Milestones are ordered by ARCHITECTURAL DEPENDENCY,
 * not feature priority. Each milestone's `declaredStatus` is reconciled by the
 * engine against live runtime probes — what the codebase actually proves.
 *
 * Grounding reflects the architectural review: the constitutional core
 * (constitution → kernel → projection-runtime → studio) is COMPLETE, but the
 * enterprise verticals (aiops/dataops/domains) do not yet execute through the
 * kernel. M3 — "Constitutionalize one vertical" — is therefore the critical
 * path: nothing downstream is real until a business workflow cannot mutate
 * state except through the kernel.
 */

import type { PlatformProgram } from "./contracts";

export const PLATFORM_PROGRAM: PlatformProgram = {
  version: "lawrence-program/v1.0",

  /* ---------------- Workstreams ---------------- */
  workstreams: [
    { id: "constitution-runtime", label: "Constitution Runtime", charter: "Root authority: ratified rules, evidence-bound decisions.", dependsOn: [] },
    { id: "enterprise-kernel", label: "Enterprise Kernel", charter: "Authority issuance, execution journal, conformance, SB-7, version graph.", dependsOn: ["constitution-runtime"] },
    { id: "enterprise-object-runtime", label: "Enterprise Object Runtime", charter: "Canonical object definitions, identity, relationships, lifecycle.", dependsOn: ["enterprise-kernel"] },
    { id: "projection-runtime", label: "Universal Projection Runtime", charter: "Object + projection + context → RenderPlan, surface-independent.", dependsOn: ["enterprise-object-runtime"] },
    { id: "host-runtime", label: "Host Runtime", charter: "Multi-host execution (server/edge/worker) + durable, replayable store.", dependsOn: ["enterprise-kernel"] },
    { id: "ai-runtime", label: "AI Runtime", charter: "AI agents produce evidence only; never decide. Lineage-tracked.", dependsOn: ["enterprise-kernel"] },
    { id: "platform-builder", label: "Platform Builder", charter: "Governed editors (ontology/projection/workflow/constitution) as projections.", dependsOn: ["projection-runtime"] },
    { id: "universal-workspace", label: "Universal Workspace", charter: "The operator surface assembled entirely from projections.", dependsOn: ["projection-runtime"] },
    { id: "runtime-explorer", label: "Runtime Explorer", charter: "Live observability over every runtime, journal, decision, replay.", dependsOn: ["enterprise-kernel"] },
    { id: "enterprise-graph", label: "Enterprise Graph", charter: "Graph-of-graphs over canonical objects, relationships, decisions.", dependsOn: ["enterprise-object-runtime"] },
    { id: "sdk-extensions", label: "SDK & Extensions", charter: "Third-party capability contracts executed under governance.", dependsOn: ["platform-builder", "host-runtime"] },
    { id: "marketplace", label: "Marketplace", charter: "Distribution of governed capabilities + objects + projections.", dependsOn: ["sdk-extensions"] },
  ],

  /* ---------------- Milestones (dependency order) ---------------- */
  milestones: [
    {
      id: "M0",
      ordinal: 0,
      label: "Constitutional Core",
      objective: "Establish the root authority and the single governed execution chokepoint.",
      architecturalOutcome: "Acyclic core: constitution → kernel. Every decision derives from ratified rules and carries evidence.",
      owningWorkstreams: ["constitution-runtime", "enterprise-kernel"],
      dependsOn: [],
      runtimeContracts: [
        { name: "Constitution.evaluate → Decision", state: "live" },
        { name: "Kernel.requestAuthority → ExecutionAuthority", state: "live" },
        { name: "ExecutionJournal.append (append-only)", state: "live", note: "in-memory module global; durability is M2" },
      ],
      enterpriseObjects: [],
      uiSurfaces: ["/constitution"],
      acceptanceCriteria: [
        "No authority is issued without a constitutional decision.",
        "Every grant and denial is journaled with evidence.",
        "Constitution imports nothing from kernel/projection (root of DAG).",
      ],
      constitutionalGates: ["Unratified article fails closed (deny).", "Missing evidence fails closed (deny)."],
      conformanceTests: ["constitution evaluates without side effects", "kernel never issues without a decision"],
      deliverables: ["constitution runtime", "kernel runtime", "/constitution surface"],
      declaredStatus: "complete",
      probes: [
        { id: "rt-has-constitution", description: "constitution + kernel runtimes registered", check: (l) => l.runtimeIds.includes("constitution") && l.runtimeIds.includes("kernel") },
        { id: "constitution-surface", description: "/constitution surface exists", check: (l) => l.surfaces.includes("/constitution") },
      ],
      epics: [
        {
          id: "M0-E1",
          label: "Governed authority issuance",
          userStories: ["As the platform, I MUST refuse any execution lacking a constitutional decision."],
          technicalTasks: ["Implement evaluation engine", "Implement Kernel.requestAuthority", "Wire evidence into decisions"],
          runtimeChanges: ["constitution-runtime", "kernel-runtime"],
          uiChanges: ["/constitution audit lens"],
          testRequirements: ["deny-on-missing-evidence", "deny-on-unratified-article"],
          risks: ["Ambient clock inside decision path breaks replay"],
          exitCriteria: ["All authority flows through one chokepoint"],
        },
      ],
    },
    {
      id: "M1",
      ordinal: 1,
      label: "Universal Projection Runtime",
      objective: "Resolve one Enterprise Object across all surfaces from a single definition.",
      architecturalOutcome: "EnterpriseObject + Projection + 4 contexts → serializable RenderPlan, rendered identically across surfaces.",
      owningWorkstreams: ["enterprise-object-runtime", "projection-runtime"],
      dependsOn: ["M0"],
      runtimeContracts: [
        { name: "EnterpriseObjectDefinition", state: "live" },
        { name: "ProjectionRuntime.resolve → RenderPlan", state: "live" },
        { name: "6 engines (validation/binding/permission/policy/layout/lifecycle)", state: "live" },
      ],
      enterpriseObjects: [{ objectType: "Candidate", state: "live" }],
      uiSurfaces: ["/studio (preview)"],
      acceptanceCriteria: [
        "One Candidate definition resolves as modal/drawer/fullPage with identical truth.",
        "Engines run client (UX) and server (defense-in-depth).",
        "Composer consumes kernel authority; buttons never mutate directly.",
      ],
      constitutionalGates: ["Surfaces never own truth.", "Resolution denied without authority."],
      conformanceTests: ["resolves only registered projections", "composeRenderPlan is pure"],
      deliverables: ["projection-runtime", "Candidate definition", "5 candidate projections"],
      declaredStatus: "complete",
      probes: [
        { id: "candidate-registered", description: "Candidate object registered", check: (l) => l.registeredObjectTypes.includes("Candidate") },
        { id: "projections-exist", description: "projections registered", check: (l) => l.registeredProjectionIds.length > 0 },
        { id: "projection-rt", description: "projection-runtime registered", check: (l) => l.runtimeIds.includes("projection-runtime") },
      ],
      epics: [
        {
          id: "M1-E1",
          label: "Surface-independent resolution",
          userStories: ["As a builder, I define an object once and it renders on every surface."],
          technicalTasks: ["RenderPlan contract", "6 engines", "composer w/ authority"],
          runtimeChanges: ["projection-runtime"],
          uiChanges: ["projection preview"],
          testRequirements: ["render-plan-determinism", "engine-parity-client-server"],
          risks: ["Only one object type seeded — universality unproven at scale"],
          exitCriteria: ["≥1 object resolves on ≥3 surfaces"],
        },
      ],
    },
    {
      id: "M2",
      ordinal: 2,
      label: "Deterministic Replay & Durable Journal",
      objective: "Make execution bit-for-bit replayable and the journal durable.",
      architecturalOutcome: "Injected clock everywhere; append-only content-hashed durable store; SB-7 reconstructability holds across process restarts.",
      owningWorkstreams: ["enterprise-kernel", "host-runtime"],
      dependsOn: ["M0"],
      runtimeContracts: [
        { name: "Injected Clock (no ambient Date.now in decision path)", state: "planned", note: "evaluation-engine.ts:265 hardcodes new Date()" },
        { name: "DurableJournal (content-hash keyed, append-only)", state: "planned", note: "journal is a module-global array today" },
        { name: "verifyReconstructability (SB-7)", state: "live" },
      ],
      enterpriseObjects: [],
      uiSurfaces: ["/kernel (Replay & SB-7)"],
      acceptanceCriteria: [
        "No runtime reads ambient wall-clock; clock is a mandatory parameter.",
        "Journal survives restart and replays to an identical state root.",
        "SB-7 reports zero blocking hidden-state risks.",
      ],
      constitutionalGates: ["Nondeterministic runtime flagged as SB-7 blocker."],
      conformanceTests: ["replay-determinism (double-fold identical)", "no-ambient-clock static check"],
      deliverables: ["durable journal adapter", "clock injection refactor"],
      declaredStatus: "in-progress",
      probes: [
        { id: "replay-det", description: "replay is deterministic", check: (l) => l.replayDeterministic },
        { id: "reconstructable", description: "SB-7 reconstructable, no blockers", check: (l) => l.reconstructable },
        { id: "durable-journal", description: "journal is durable (not in-memory)", check: () => false /* not yet: module-global array */ },
      ],
      epics: [
        {
          id: "M2-E1",
          label: "Eliminate ambient time",
          userStories: ["As an auditor, I MUST be able to replay any execution to an identical result."],
          technicalTasks: ["Remove Date.now() defaults", "Fix evaluation-engine.ts:265", "Thread clock through all runtimes"],
          runtimeChanges: ["constitution-runtime", "kernel-runtime", "projection-runtime"],
          uiChanges: ["/kernel replay panel shows injected clock"],
          testRequirements: ["static lint: no Date.now in lib/", "replay equivalence"],
          risks: ["Every caller must inject clock or replay silently diverges"],
          exitCriteria: ["Zero ambient-clock reads in the core"],
        },
        {
          id: "M2-E2",
          label: "Durable append-only journal",
          userStories: ["As the platform, my journal MUST survive restarts."],
          technicalTasks: ["Neon-backed append-only event store", "content-hash idempotency", "hydrate-on-boot"],
          runtimeChanges: ["host-runtime", "kernel-runtime"],
          uiChanges: ["/kernel journal shows durable source"],
          testRequirements: ["restart-then-replay equivalence"],
          risks: ["Dual source of truth if in-memory cache drifts from store"],
          exitCriteria: ["Journal reconstructable from store alone"],
        },
      ],
    },
    {
      id: "M3",
      ordinal: 3,
      label: "Constitutionalize One Vertical (CRITICAL PATH)",
      objective: "Make one real business workflow execute exclusively through the kernel.",
      architecturalOutcome: "A vertical (recruiting or claims) registers its objects in the object runtime and routes every state change through Kernel.requestAuthority → journal. The OS governs the product, not just itself.",
      owningWorkstreams: ["enterprise-object-runtime", "enterprise-kernel", "projection-runtime"],
      dependsOn: ["M1", "M2"],
      runtimeContracts: [
        { name: "Vertical actions → Kernel.requestAuthority (no ad-hoc chokepoint)", state: "planned", note: "verticals import kernel 0× today" },
        { name: "Vertical objects registered as EnterpriseObjectDefinition", state: "planned" },
      ],
      enterpriseObjects: [
        { objectType: "Requisition", state: "planned" },
        { objectType: "Submission", state: "planned" },
        { objectType: "Placement", state: "planned" },
      ],
      uiSurfaces: ["/workspace (vertical operating surface as projections)"],
      acceptanceCriteria: [
        "No vertical state change occurs except through the kernel chokepoint.",
        "Vertical objects are registered Enterprise Objects (no shadow models).",
        "Every vertical action emits a journal entry with evidence.",
        "Legacy *-workflow-service ad-hoc chokepoints are removed or wrapped.",
      ],
      constitutionalGates: ["Ungoverned mutation path fails CI (no direct store writes).", "High-risk vertical action routes to approval."],
      conformanceTests: ["vertical-action-is-journaled", "no-shadow-object-models", "no-direct-store-write"],
      deliverables: ["recruiting/claims on the runtime", "removal of bespoke workflow services"],
      declaredStatus: "planned",
      probes: [
        { id: "vertical-governed", description: "≥1 vertical routes through the kernel", check: (l) => l.governedVerticals.length > 0 },
      ],
      epics: [
        {
          id: "M3-E1",
          label: "Register vertical Enterprise Objects",
          userStories: ["As a recruiter, the Requisition I act on is the SAME canonical object the runtime serves."],
          technicalTasks: ["Define Requisition/Submission/Placement definitions", "Migrate domain models to registry", "Author projections"],
          runtimeChanges: ["enterprise-object-runtime", "projection-runtime"],
          uiChanges: ["/workspace recruiting projections"],
          testRequirements: ["no-shadow-object-models"],
          risks: ["Large existing domain code (~53 files) to migrate"],
          exitCriteria: ["Vertical objects resolve via projection-runtime"],
        },
        {
          id: "M3-E2",
          label: "Route vertical actions through the kernel",
          userStories: ["As the platform, a placement MUST NOT be created except via a governed action."],
          technicalTasks: ["Replace recruiting-workflow-service with kernel actions", "Emit evidence-bound journal entries", "Approval routing for high-risk"],
          runtimeChanges: ["enterprise-kernel"],
          uiChanges: ["/workspace governed action buttons"],
          testRequirements: ["vertical-action-is-journaled", "no-direct-store-write CI gate"],
          risks: ["N competing ad-hoc chokepoints across aiops/dataops/domains"],
          exitCriteria: ["Zero ungoverned mutation paths in the chosen vertical"],
        },
      ],
    },
    {
      id: "M4",
      ordinal: 4,
      label: "AI Runtime (evidence-only)",
      objective: "Let AI agents produce evidence and recommendations — never decisions.",
      architecturalOutcome: "AI output enters only as Evidence → Recommendation → Patch; the kernel still decides. Lineage-tracked, replayable.",
      owningWorkstreams: ["ai-runtime"],
      dependsOn: ["M3"],
      runtimeContracts: [
        { name: "AIEvidence (provenance + lineage)", state: "planned" },
        { name: "AI cannot promote/decide (constitutional invariant)", state: "planned" },
      ],
      enterpriseObjects: [{ objectType: "Recommendation", state: "planned" }],
      uiSurfaces: ["/studio (AI-assisted patches)"],
      acceptanceCriteria: [
        "AI-authored evidence carries provenance and is replay-stable.",
        "No AI path can mutate state without passing the kernel gate.",
      ],
      constitutionalGates: ["AI-authored action requires same authority as human.", "AI cannot self-approve."],
      conformanceTests: ["ai-cannot-decide", "ai-evidence-carries-lineage"],
      deliverables: ["AI runtime adapter", "lineage tracking"],
      declaredStatus: "planned",
      probes: [{ id: "ai-runtime", description: "AI runtime registered", check: (l) => l.runtimeIds.includes("ai-runtime") }],
      epics: [
        {
          id: "M4-E1",
          label: "Evidence-only AI",
          userStories: ["As a builder, AI suggestions reach state only through the governed patch chain."],
          technicalTasks: ["AI evidence contract", "lineage record", "wire to projection-studio chain"],
          runtimeChanges: ["ai-runtime"],
          uiChanges: ["studio AI recommendation cards"],
          testRequirements: ["ai-cannot-decide"],
          risks: ["Nondeterministic model output threatens replay — must snapshot outputs as evidence"],
          exitCriteria: ["AI output is replayable evidence, never a decision"],
        },
      ],
    },
    {
      id: "M5",
      ordinal: 5,
      label: "Platform Builder (self-hosting)",
      objective: "Editors become projections over Enterprise Objects, not bespoke code.",
      architecturalOutcome: "Ontology Designer, Projection Builder, Workflow Builder, Constitution Editor are themselves LAWRENCE-built artifacts that persist governed changes.",
      owningWorkstreams: ["platform-builder"],
      dependsOn: ["M3"],
      runtimeContracts: [
        { name: "applyPatch persists a governed ProjectionDefinition", state: "planned", note: "applyPatch is preview-only today" },
        { name: "Editors-as-projections", state: "planned" },
      ],
      enterpriseObjects: [
        { objectType: "ProjectionDefinition", state: "planned" },
        { objectType: "WorkflowDefinition", state: "planned" },
      ],
      uiSurfaces: ["/studio (write)", "/builder"],
      acceptanceCriteria: [
        "Studio applyPatch writes a governed, journaled definition.",
        "At least one editor is itself a projection (eats its own dog food).",
      ],
      constitutionalGates: ["Builder edits route through the same kernel as runtime.", "No direct registry mutation."],
      conformanceTests: ["builder-edit-is-journaled", "editor-is-a-projection"],
      deliverables: ["governed applyPatch", "ontology/projection/workflow editors"],
      declaredStatus: "planned",
      probes: [{ id: "builder-surface", description: "/builder surface exists", check: (l) => l.surfaces.includes("/builder") }],
      epics: [
        {
          id: "M5-E1",
          label: "Close the governed write loop",
          userStories: ["As a builder, my edit becomes a governed, persisted, replayable change."],
          technicalTasks: ["Persist applyPatch via kernel", "Version the definition", "Journal the change"],
          runtimeChanges: ["platform-builder", "enterprise-kernel"],
          uiChanges: ["studio write mode"],
          testRequirements: ["builder-edit-is-journaled"],
          risks: ["Persistence without governance reintroduces ungoverned writes"],
          exitCriteria: ["A projection built in Studio is served by the runtime"],
        },
      ],
    },
    {
      id: "M6",
      ordinal: 6,
      label: "SDK, Extensions & Marketplace",
      objective: "Third parties ship governed capabilities, objects, and projections.",
      architecturalOutcome: "Capability contracts execute under the same constitution; the marketplace distributes LAWRENCE-built artifacts.",
      owningWorkstreams: ["sdk-extensions", "marketplace"],
      dependsOn: ["M5"],
      runtimeContracts: [
        { name: "CapabilityContract (sandboxed, governed)", state: "planned" },
        { name: "Marketplace publish/install (governed)", state: "planned" },
      ],
      enterpriseObjects: [{ objectType: "Extension", state: "planned" }, { objectType: "Capability", state: "planned" }],
      uiSurfaces: ["/marketplace"],
      acceptanceCriteria: [
        "Extensions cannot bypass the kernel.",
        "Installing a capability is a governed, journaled action.",
      ],
      constitutionalGates: ["Extension capability gated by constitution.", "Untrusted code runs only via contracts."],
      conformanceTests: ["extension-cannot-bypass-kernel", "install-is-governed"],
      deliverables: ["extension SDK", "marketplace"],
      declaredStatus: "planned",
      probes: [{ id: "marketplace-surface", description: "/marketplace surface exists", check: (l) => l.surfaces.includes("/marketplace") }],
      epics: [
        {
          id: "M6-E1",
          label: "Governed capability contracts",
          userStories: ["As a developer, my extension runs under the same constitution as the core."],
          technicalTasks: ["Capability contract spec", "sandbox host", "publish/install actions"],
          runtimeChanges: ["sdk-extensions", "marketplace", "host-runtime"],
          uiChanges: ["/marketplace listing + install"],
          testRequirements: ["extension-cannot-bypass-kernel"],
          risks: ["Sandbox escape = constitutional breach"],
          exitCriteria: ["Third-party capability executes governed end-to-end"],
        },
      ],
    },
  ],

  /* ---------------- Self-hosting artifacts ---------------- */
  selfHosting: [
    { id: "projection-builder", label: "Projection Builder", becomesSelfHostedAt: "M5", state: "partial", note: "Studio compiles/validates live but applyPatch is preview-only." },
    { id: "ontology-designer", label: "Ontology Designer", becomesSelfHostedAt: "M5", state: "bespoke", note: "Object definitions are hand-written TS today." },
    { id: "workflow-builder", label: "Workflow Builder", becomesSelfHostedAt: "M5", state: "bespoke", note: "Workflows live in ad-hoc vertical services." },
    { id: "constitution-editor", label: "Constitution Editor", becomesSelfHostedAt: "M5", state: "bespoke", note: "Constitution is code; editing is a governed-write problem." },
    { id: "runtime-builder", label: "Runtime Builder", becomesSelfHostedAt: "M6", state: "bespoke", note: "Runtimes are hand-authored; contracts are formalized (SB-7 #6)." },
    { id: "extension-sdk", label: "Extension SDK", becomesSelfHostedAt: "M6", state: "bespoke", note: "Not started." },
    { id: "marketplace", label: "Marketplace", becomesSelfHostedAt: "M6", state: "bespoke", note: "Not started." },
  ],

  /* ---------------- Production readiness ---------------- */
  productionStages: [
    {
      id: "developer-preview",
      label: "Developer Preview",
      requiresMilestones: ["M0", "M1"],
      performance: "Best-effort; single-host.",
      governance: "Core self-governed; verticals may be ungoverned.",
      replay: "In-memory replay within a process.",
      observability: "Runtime Explorer over core runtimes.",
      security: "Single-tenant, no external trust boundary.",
      conformance: "Core conformance suite green.",
    },
    {
      id: "alpha",
      label: "Alpha",
      requiresMilestones: ["M0", "M1", "M2"],
      performance: "Deterministic replay; bounded latency.",
      governance: "Durable journal of record.",
      replay: "Reconstructable across restarts (SB-7, zero blockers).",
      observability: "Replay + journal visibility.",
      security: "Authn/z on governance surfaces.",
      conformance: "Core + replay conformance green.",
    },
    {
      id: "beta",
      label: "Beta",
      requiresMilestones: ["M0", "M1", "M2", "M3"],
      performance: "Production latency budget on one vertical.",
      governance: "≥1 vertical fully constitutional; zero ungoverned mutation in it.",
      replay: "Vertical workflows replayable end-to-end.",
      observability: "Vertical actions visible in Runtime Explorer.",
      security: "Per-tenant isolation; approval routing live.",
      conformance: "Vertical conformance suite green.",
    },
    {
      id: "release-candidate",
      label: "Release Candidate",
      requiresMilestones: ["M0", "M1", "M2", "M3", "M4", "M5"],
      performance: "Multi-vertical at target SLOs.",
      governance: "AI evidence-only enforced; governed builder writes.",
      replay: "Full platform replay incl. AI evidence + builder edits.",
      observability: "End-to-end lineage.",
      security: "Pen-tested; extension sandbox boundary verified.",
      conformance: "All suites green incl. ai-cannot-decide, builder-edit-is-journaled.",
    },
    {
      id: "v1.0",
      label: "v1.0",
      requiresMilestones: ["M0", "M1", "M2", "M3", "M4", "M5", "M6"],
      performance: "Marketplace-scale, multi-host.",
      governance: "Constitution governs core, verticals, AI, and third-party extensions.",
      replay: "Whole-system reconstructable from canonical sources alone.",
      observability: "Full Runtime Explorer + Enterprise Graph.",
      security: "Third-party capabilities cannot bypass the kernel.",
      conformance: "100% conformance + zero SB-7 blockers across all runtimes.",
    },
  ],
};
