// Seed canonical relationships (ONT-002 §Seed). Two classes:
//   - ACTIVE: edges in use today (kept in lockstep with linkObjects callers so the
//     live graph validates clean).
//   - PLANNED (future-safe): declared now so the contract is stable, but their
//     endpoint object types are intentionally NOT implemented in this slice
//     (Interview/Offer/Placement/Mission/Recommendation). Declaring them is not
//     implementing them.

import type { RelationshipDefinition } from "./types";

const GOV = { owner: "LAWRENCE Architecture Council", since: "1.0" } as const;
const stable = { ...GOV, stability: "stable" as const };
const experimental = { ...GOV, stability: "experimental" as const };

/** Declarative defaults shared by seed defs (no runtime effect in VS-003). */
const DECLARED: Pick<RelationshipDefinition, "emittedEvents" | "permissions"> = {
  emittedEvents: ["ontology.relationship.created", "ontology.relationship.removed"],
  permissions: { create: "ontology.admin", remove: "ontology.admin" },
};

export const RELATIONSHIP_DEFINITIONS: readonly RelationshipDefinition[] = [
  // ── Recruiting core (ACTIVE) ──────────────────────────────────────────────
  {
    id: "candidate_submitted_submission",
    linkType: "submitted",
    sourceType: "Candidate",
    targetType: "Submission",
    inverseRelationship: null,
    cardinality: "one_to_many",
    description: "A candidate produced this submission.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "submission_targets_job",
    linkType: "targets",
    sourceType: "Submission",
    targetType: "Job",
    inverseRelationship: null,
    cardinality: "many_to_one",
    description: "A submission is against this job.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "job_for_account",
    linkType: "for",
    sourceType: "Job",
    targetType: "Account",
    inverseRelationship: null,
    cardinality: "many_to_one",
    description: "A job belongs to this client account.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "candidate_associated_with_account",
    linkType: "associated_with",
    sourceType: "Candidate",
    targetType: "Account",
    inverseRelationship: null,
    cardinality: "many_to_many",
    description: "A candidate is associated with a client account (e.g. submitted/placed).",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "candidate_owned_by_recruiter",
    linkType: "owned_by",
    sourceType: "Candidate",
    targetType: "Recruiter",
    inverseRelationship: null,
    cardinality: "many_to_one",
    description: "A candidate is owned/represented by a recruiter.",
    lifecycle: "active",
    governance: experimental,
    ...DECLARED,
  },
  {
    id: "submission_owned_by_recruiter",
    linkType: "owned_by",
    sourceType: "Submission",
    targetType: "Recruiter",
    inverseRelationship: null,
    cardinality: "many_to_one",
    description: "A submission is owned by a recruiter.",
    lifecycle: "active",
    governance: experimental,
    ...DECLARED,
  },

  // ── Existing cross-domain annotation / containment edges (ACTIVE) ──────────
  {
    id: "recruiter_note_about_candidate",
    linkType: "about",
    sourceType: "RecruiterNote",
    targetType: "Candidate",
    inverseRelationship: null,
    cardinality: "many_to_one",
    description: "A recruiter note annotates a candidate.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "recruiter_note_for_job",
    linkType: "for",
    sourceType: "RecruiterNote",
    targetType: "Job",
    inverseRelationship: null,
    cardinality: "many_to_one",
    description: "A recruiter note is filed against a job.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "decision_memo_about_account",
    linkType: "about",
    sourceType: "DecisionMemo",
    targetType: "Account",
    inverseRelationship: null,
    cardinality: "many_to_one",
    description: "An executive decision memo is about an account.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "onboarding_task_for_case",
    linkType: "for",
    sourceType: "OnboardingTask",
    targetType: "OnboardingCase",
    inverseRelationship: "onboarding_case_has_task",
    cardinality: "many_to_one",
    description: "An onboarding task belongs to an onboarding case.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "onboarding_case_has_task",
    linkType: "onboarding.case_has_task",
    sourceType: "OnboardingCase",
    targetType: "OnboardingTask",
    inverseRelationship: "onboarding_task_for_case",
    cardinality: "one_to_many",
    description: "An onboarding case contains onboarding tasks.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "validation_finding_of_case",
    linkType: "finding_of",
    sourceType: "ValidationFinding",
    targetType: "ValidationCase",
    inverseRelationship: null,
    cardinality: "many_to_one",
    description: "A validation finding belongs to a validation case.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },
  {
    id: "support_draft_for_ticket",
    linkType: "draft_for",
    sourceType: "SupportDraftResponse",
    targetType: "SupportTicket",
    inverseRelationship: null,
    cardinality: "many_to_one",
    description: "A drafted support response is for a support ticket.",
    lifecycle: "active",
    governance: stable,
    ...DECLARED,
  },

  // ── Future-safe (PLANNED — declared only; endpoints NOT implemented) ───────
  {
    id: "submission_has_interview",
    linkType: "has_interview",
    sourceType: "Submission",
    targetType: "Interview",
    inverseRelationship: null,
    cardinality: "one_to_many",
    description: "A submission accumulates interviews (future object type).",
    lifecycle: "planned",
    governance: experimental,
    ...DECLARED,
  },
  {
    id: "interview_resulted_in_offer",
    linkType: "resulted_in_offer",
    sourceType: "Interview",
    targetType: "Offer",
    inverseRelationship: null,
    cardinality: "one_to_one",
    description: "An interview process results in an offer (future object type).",
    lifecycle: "planned",
    governance: experimental,
    ...DECLARED,
  },
  {
    id: "offer_resulted_in_placement",
    linkType: "resulted_in_placement",
    sourceType: "Offer",
    targetType: "Placement",
    inverseRelationship: null,
    cardinality: "one_to_one",
    description: "An accepted offer results in a placement (future object type).",
    lifecycle: "planned",
    governance: experimental,
    ...DECLARED,
  },
  {
    id: "mission_produces_recommendation",
    linkType: "produces",
    sourceType: "Mission",
    targetType: "Recommendation",
    inverseRelationship: null,
    cardinality: "one_to_many",
    description: "A mission produces recommendations (future object type).",
    lifecycle: "planned",
    governance: experimental,
    ...DECLARED,
  },
];
